[[swarm]]
name = "home-swarm"
tags = ["homelab"]

[swarm.config]
servers = ["sentinel-0"]

[[stack]]
name = "homelab-networking"
tags = ["homelab", "dns"]
deploy = true

[stack.config]
swarm = "home-swarm"
repo = "fabricesemti80/home-dc-service-hosts"
branch = "main"
file_paths = ["docker-stacks/networking/docker-compose.yml"]
environment = """
TAILSCALE_OAUTH_CLIENT_ID = [[TAILSCALE_OAUTH_CLIENT_ID]]
TAILSCALE_OAUTH_CLIENT_SECRET = [[TAILSCALE_OAUTH_CLIENT_SECRET]]
TECHNITIUM_ADMIN_PASSWORD = [[TECHNITIUM_ADMIN_PASSWORD]]
TECHNITIUM_NODE0_HOSTNAME = [[TECHNITIUM_NODE0_HOSTNAME]]
TECHNITIUM_NODE1_HOSTNAME = [[TECHNITIUM_NODE1_HOSTNAME]]
TECHNITIUM_NODE2_HOSTNAME = [[TECHNITIUM_NODE2_HOSTNAME]]
TECHNITIUM_NODE0_TOKEN = [[TECHNITIUM_NODE0_TOKEN]]
TECHNITIUM_NODE1_TOKEN = [[TECHNITIUM_NODE1_TOKEN]]
TECHNITIUM_NODE2_TOKEN = [[TECHNITIUM_NODE2_TOKEN]]
"""

[[stack]]
name = "homelab-monitoring"
tags = ["homelab", "monitoring"]
deploy = true

[stack.config]
swarm = "home-swarm"
repo = "fabricesemti80/home-dc-service-hosts"
branch = "main"
file_paths = ["docker-stacks/monitoring/docker-compose.yml"]
environment = """
PULSE_HOSTNAME = [[PULSE_HOSTNAME]]
"""

[[resource_sync]]
name = "home-dc-service-hosts"
tags = ["homelab"]

[resource_sync.config]
repo = "fabricesemti80/home-dc-service-hosts"
branch = "main"
resource_path = ["komodo/resources.toml"]
