---
all:
  children:
    proxmox_guests:
      children:
        proxmox_debian_guests:
          hosts:
            proxmox-pbs-0:
              ansible_host: 10.0.40.16
              ansible_user: root
              ansible_ssh_private_key_file: ~/.ssh/fs_home_rsa
              guest_kind: lxc
            docker-svc-0:
              ansible_host: 10.0.40.54
              ansible_user: fs
              ansible_ssh_private_key_file: ~/.ssh/fs_home_rsa
              guest_kind: vm
              docker_users:
                - fs

        proxmox_backup_servers:
          hosts:
            proxmox-pbs-0:
              pbs_datastore_mount_strategy: nfs

    physical_debian_hosts:
      hosts:
        sentinel-0:
          ansible_host: 10.0.40.55
          ansible_user: fs
          ansible_ssh_private_key_file: ~/.ssh/fs_home_rsa
          ansible_become_password: "{{ lookup('ansible.builtin.env', 'ANSI_ROOT_PASSWORD') }}"
          guest_kind: physical
          debian_base_static_ipv4_address: 10.0.40.55/24
          debian_base_static_ipv4_gateway: 10.0.40.1
          docker_add_repo: false
          docker_users:
            - fs
        sentinel-1:
          ansible_host: 10.0.40.53
          ansible_user: fs
          ansible_ssh_private_key_file: ~/.ssh/fs_home_rsa
          ansible_become_password: "{{ lookup('ansible.builtin.env', 'ANSI_ROOT_PASSWORD') }}"
          guest_kind: physical
          debian_base_static_ipv4_address: 10.0.40.53/24
          debian_base_static_ipv4_gateway: 10.0.40.1
          docker_add_repo: false
          containerd_root: /srv/containerd
          docker_daemon_options:
            data-root: /srv/docker-data
          docker_users:
            - fs

    debian_service_hosts:
      children:
        proxmox_debian_guests:
        physical_debian_hosts:

    docker_standalone_hosts:
      children:
        portainer_server_hosts:
          hosts:
            docker-svc-0:
              tailscale_advertise_tags: "tag:server,tag:container"
        portainer_agent_hosts:
          hosts:
            docker-svc-0:
            sentinel-0:
            sentinel-1:

    docker_swarm:
      children:
        docker_swarm_managers:
          hosts:
            sentinel-1:
              docker_swarm_advertise_addr: 10.0.40.53
        docker_swarm_workers:
          hosts:
            docker-svc-0:
