services:
  pulse:
    image: rcourtman/pulse:latest
    volumes:
      - /srv/docker/pulse/data:/data
    environment:
      TZ: Europe/London
      NODE_NAME: pulse-server
    networks:
      - homelab_proxy_swarm
    ports:
      - target: 7655
        published: 17655
        protocol: tcp
        mode: host
    deploy:
      placement:
        constraints:
          - node.hostname == sentinel-1
      restart_policy:
        condition: any
    labels:
      docktail.service.enable: "true"
      docktail.service.direct: "false"
      docktail.service.name: pulse
      docktail.service.port: "7655"
      docktail.service.service-port: "443"
      docktail.service.protocol: http
      homepage.group: Monitoring
      homepage.name: Pulse
      homepage.icon: mdi-pulse
      homepage.href: https://pulse.koala-dominant.ts.net

networks:
  homelab_proxy_swarm:
    external: true
