name: networking

services:
  technitium:
    image: docker.io/technitium/dns-server:latest
    container_name: technitium
    hostname: dns-server
    restart: unless-stopped
    networks:
      - homelab_proxy
    ports:
      - target: 53
        published: 53
        protocol: tcp
        mode: host
      - target: 53
        published: 53
        protocol: udp
        mode: host
    environment:
      DNS_SERVER_DOMAIN: dns-server
      DNS_SERVER_ADMIN_PASSWORD: ${TECHNITIUM_ADMIN_PASSWORD}
      DNS_SERVER_WEB_SERVICE_LOCAL_ADDRESSES: 0.0.0.0
      DNS_SERVER_WEB_SERVICE_HTTP_PORT: "5380"
      DNS_SERVER_WEB_SERVICE_ENABLE_HTTPS: "false"
    volumes:
      - technitium_data:/etc/dns
    labels:
      docktail.service.enable: "true"
      docktail.service.name: technitium
      docktail.service.port: "5380"
      docktail.service.service-port: "443"
      docktail.service.protocol: http

volumes:
  technitium_data:
    name: technitium_data

networks:
  homelab_proxy:
    external: true
