---
- name: Ensure systemd-resolved is stopped, disabled and masked
  ansible.builtin.systemd:
    name: systemd-resolved
    state: stopped
    enabled: false
    masked: true
  ignore_errors: true

- name: Ensure static resolv.conf replaces systemd-resolved stub
  ansible.builtin.copy:
    dest: /etc/resolv.conf
    mode: "0644"
    content: |
      {% for ns in disable_systemd_resolved_nameservers %}
      nameserver {{ ns }}
      {% endfor %}
      {% if disable_systemd_resolved_search_domains | length > 0 %}
      search {{ disable_systemd_resolved_search_domains | join(' ') }}
      {% endif %}
